version: "3"

services:
#  web-app-using-aws-otel-collector-and-agent:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - JAVA_TOOL_OPTIONS="-javaagent:/otel/aws-opentelemetry-agent.jar"
#      - EXTERNAL_ENDPOINT=https://example.com
#      - OTEL_METRICS_EXPORTER=otlp
#      - OTEL_TRACES_EXPORTER=otlp
#      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aws-otel-collector:4317
#      - OTEL_RESOURCE_ATTRIBUTES="service.name=web-app-using-aws-otel,service.namespace=dev"
  web-app-using-otel-collector-and-agent:
    build: .
    ports:
      - "8081:8080"
      - "9464:9464"
    environment:
      - JAVA_TOOL_OPTIONS="-javaagent:/otel/opentelemetry-javaagent.jar"
      - EXTERNAL_ENDPOINT=https://example.com
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
#      - OTEL_METRICS_EXPORTER=prometheus
#      - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES="service.name=web-app-using-otel,service.namespace=dev"

  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./configs/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:7.3.6
    volumes:
      - ./configs/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./configs/grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./configs/grafana/metrics.json:/var/lib/grafana/dashboards/metrics.json
    ports:
      - "3000:3000"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:0.44.0
    command: [ "--config=/etc/otel-agent-config.yaml" ]
    volumes:
      - ./configs/otel/otel-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1778:1777"   # pprof extension
      - "55680:55679" # zpages extension
      - "13134:13133" # health_check
      - "8898:8888"   # Prometheus metrics exposed by the collector
      - "8899:8889"   # Prometheus exporter metrics
      - "4318:4318"   # OTLP gRPC receiver
#  aws-otel-collector:
#    image: public.ecr.aws/aws-observability/aws-otel-collector:v0.16.0
#    command: [ "--config=/etc/otel-agent-config.yaml" ]
#    volumes:
#      - ./configs/otel-aws/otel-config.yaml:/etc/otel-agent-config.yaml
#      - ~/.aws:/root/.aws
#    environment:
#      - AWS_REGION=us-east-1
#      - AWS_ACCESS_KEY_ID=**
#      - AWS_SECRET_ACCESS_KEY=**
#      - PROMETHEUS_WRITE_ENDPOINT=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-**/api/v1/remote_write
#    ports:
#      - "1777:1777"   # pprof extension
#      - "55679:55679" # zpages extension
#      - "13133:13133" # health_check
#      - "8888:8888"   # Prometheus metrics exposed by the collector
#      - "8889:8889"   # Prometheus exporter metrics
#      - "4317:4317"   # OTLP gRPC receiver

  traffic-generator:
    image: ellerbrock/alpine-bash-curl-ssl:latest
#    command: [ "/bin/bash", "-c", "sleep 20; while :; do curl web-app-using-aws-otel-collector-and-agent:8080/hello-world > /dev/null 1>&1; sleep 2; curl web-app-using-otel-collector-and-agent:8080/hello-world > /dev/null 2>&1; sleep 5; done" ]
    command: [ "/bin/bash", "-c", "sleep 20; curl web-app-using-otel-collector-and-agent:8080/hello-world > /dev/null 1>&1; sleep 2; curl web-app-using-otel-collector-and-agent:8080/hello-world?name=call > /dev/null 1>&1; sleep 2; curl web-app-using-otel-collector-and-agent:8080/hello-world?name=error > /dev/null 1>&1; while :; do curl  web-app-using-otel-collector-and-agent:8080/hello-world > /dev/null 1>&1; sleep 5; done" ]
    depends_on:
      - web-app-using-otel-collector-and-agent
#  aws-traffic-generator:
#    image: ellerbrock/alpine-bash-curl-ssl:latest
#    #    command: [ "/bin/bash", "-c", "sleep 20; while :; do curl web-app-using-aws-otel-collector-and-agent:8080/hello-world > /dev/null 1>&1; sleep 2; curl web-app-using-otel-collector-and-agent:8080/hello-world > /dev/null 2>&1; sleep 5; done" ]
#    command: [ "/bin/bash", "-c", "sleep 20; curl web-app-using-aws-otel-collector-and-agent:8080/hello-world > /dev/null 1>&1; sleep 2; curl web-app-using-aws-otel-collector-and-agent:8080/hello-world?name=call > /dev/null 1>&1; sleep 2; curl web-app-using-aws-otel-collector-and-agent:8080/hello-world?name=error > /dev/null 1>&1; while :; do curl  web-app-using-aws-otel-collector-and-agent:8080/hello-world > /dev/null 1>&1; sleep 5; done" ]
#    depends_on:
#      - web-app-using-aws-otel-collector-and-agent
