template: Hello, %s!
defaultName: Stranger

# Logging settings.
logging:
  level: ${LOG_LEVEL:-INFO}

  appenders:
    - type: console
      threshold: DEBUG
      logFormat: "[%-5p] [%d{ISO8601,UTC}] [%X{AWS-XRAY-TRACE-ID}] [traceId: %X{trace_id} spanId: %X{span_id}] %c: %m%n%rEx"
