{
 "title": "Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query_param", "query": "label_values(api_param)" }
  ]
 },
 "panels": [
  {
   "title": "API Invocation Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "api_invocation", "legendFormat": "{{api_param}}" },
    {}
   ]
  },
  {
   "title": "API Invocation Counter from histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "api_latency_count", "legendFormat": "{{api_param}}" },
    {}
   ]
  },
  {
   "title": "API Latency Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_latency_sum/api_latency_count",
     "legendFormat": "{{api_param}}"
    }
   ]
  },
  {
   "title": "API Histogram (Filtered by dropdown)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (increase(api_latency_bucket{api_param=\"$query_param\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}